### PR TITLE
Allow for custom channels on route change.

### PR DESCRIPTION
**Pull request by ghost**
It is necessary on large single page apps to mutate the app state in some way when the route uri changes. This pull request adds route based callbacks for when the route uri changes. This addresses my concerns in #16 . All of the tests still pass.

### CODE REVIEW

**Comment by nikuda** [comment]
I don't think this should have been merged. It seems to duplicate existing functionality and more importantly has no tests/use cases. @twilson63 

In #16:

> When writing large single page applications, it would be nice to be able to listen for changes on a route, and perform some ajax/other side effect work when the route state get's mutated.

``` js
var state = mercury.struct({
  route: Router()
});
```

`route` in this case is an observable, changes of which can be listened to:

``` js
state.route(function (change) {
  console.log(change)
})
```

And more importantly:

> For example, if '/animals' changes to 'animals/:id', do some work to load that resource into the app state. Is there a built in way to do this, or do I have to modify the router to get it to work? I apologize if this is a stupid question, I'm still new to mercury.

This is the whole point of `mercury-router`, and `route-view` in particular:

``` js
routeView({
  '/': renderHome,
  '/animals': renderAnimals,
  '/animals/:id': renderAnimalItem
}, { route: state.route })
```

If you want to make requests you can either observe `state.route` or have specific channel events to trigger them.

**Comment by nikuda** [comment]
@coballast can you confirm that the above suggestions work for you?

**Comment by twilson63** [comment]
@nikuda

Thanks for your pull request, I made you a collaborator so that you can
make any adjustments, share your npm uid and I will give you publish rights.

Thanks

Tom

On Thu, Mar 31, 2016 at 6:58 PM, nikuda notifications@github.com wrote:

> @coballast https://github.com/coballast can you confirm that the above
> suggestions work for you?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/twilson63/mercury-router/pull/17#issuecomment-204164030

## 

Tom Wilson
Jack Russell Software, A Tabula Rasa Healthcare Division
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-606-6484
Mobile: 843-469-5856
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_York
http://www.jackhq.com/calendar

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.

**Comment by coballast** [comment]
@nikuda Will this observable also fire when the route get's an initial value when the app first loads?

**Comment by ghost** [comment]
I don't mind if you guys remove it.

**Comment by nikuda** [comment]
Thanks @twilson63. My NPM uid is `nikuda`.

I will revert the changes made in this PR when I get a free moment. Documentation is probably what needs to be updated too, to make usage clearer.

**Pull request merged**
